{
	"version": 1732772366,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/mario-sheet0.png",
		"images/mario-sheet1.png",
		"images/mario-sheet2.png",
		"images/camera-sheet0.png",
		"images/wall-sheet0.png",
		"images/cameradisable-sheet0.png",
		"images/flag-sheet0.png",
		"images/castleflag-sheet0.png",
		"images/firework-sheet0.png",
		"images/firework-sheet1.png",
		"images/firework-sheet2.png",
		"images/castledoor-sheet0.png",
		"images/flagpole-sheet0.png",
		"images/mushroom-sheet0.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/coin-sheet2.png",
		"images/fakecoin-sheet0.png",
		"images/itemblock-sheet0.png",
		"images/itemblock-sheet1.png",
		"images/itemblock-sheet2.png",
		"images/itemblock_hitbox-sheet0.png",
		"images/breakableblock-sheet0.png",
		"images/breakableblock-sheet1.png",
		"images/breakableblock_hitbox-sheet0.png",
		"images/breakableblock_particle-sheet0.png",
		"images/breakableblock_particle-sheet1.png",
		"images/goomba-sheet0.png",
		"images/goomba-sheet1.png",
		"images/goomba-sheet2.png",
		"images/koopa_troopa-sheet0.png",
		"images/background.png",
		"images/pipe_entry-sheet0.png",
		"images/pipe_exit-sheet0.png",
		"images/pipe_camera-sheet0.png",
		"images/text.png",
		"images/sprite-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite5-sheet0.png",
		"media/1-up.m4a",
		"media/1-up.ogg",
		"media/bowser falls.m4a",
		"media/bowser falls.ogg",
		"media/bowser fire.m4a",
		"media/bowser fire.ogg",
		"media/breakblock.m4a",
		"media/breakblock.ogg",
		"media/bump.m4a",
		"media/bump.ogg",
		"media/coin.m4a",
		"media/coin.ogg",
		"media/fireball.m4a",
		"media/fireball.ogg",
		"media/fireworks.m4a",
		"media/fireworks.ogg",
		"media/flagpole.m4a",
		"media/flagpole.ogg",
		"media/gameover.m4a",
		"media/gameover.ogg",
		"media/jump small.m4a",
		"media/jump small.ogg",
		"media/jump super.m4a",
		"media/jump super.ogg",
		"media/kick.m4a",
		"media/kick.ogg",
		"media/mario die.m4a",
		"media/mario dies.ogg",
		"media/pause.m4a",
		"media/pause.ogg",
		"media/pipe.m4a",
		"media/pipe.ogg",
		"media/powerup appears.m4a",
		"media/powerup appears.ogg",
		"media/powerup.m4a",
		"media/powerup.ogg",
		"media/stage clear.m4a",
		"media/stage clear.ogg",
		"media/stomp.m4a",
		"media/stomp.ogg",
		"media/vine.m4a",
		"media/vine.ogg",
		"media/warning.m4a",
		"media/warning.ogg",
		"media/world clear.m4a",
		"media/world clear.ogg",
		"media/point.m4a",
		"media/point.ogg",
		"media/lagu-ff-season-1-pertama-kali-garena-free-fire.ogg",
		"media/ground theme.m4a",
		"media/ground theme.ogg",
		"media/underground theme.m4a",
		"media/underground theme.ogg",
		"media/ground theme (fast).m4a",
		"media/ground theme (fast).ogg",
		"media/underground theme (fast).m4a",
		"media/underground theme (fast).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}